FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl vim && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# Сначала создаём пользователя
RUN useradd -u 1000 appuser

# Затем меняем владельца и права на файлы
RUN chown -R appuser:appuser /app && \
    chmod -R 755 /app

# Переключаемся на пользователя appuser
USER appuser

EXPOSE 5000
ENV FLASK_ENV=production

CMD ["python", "app.py"]

