name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 4: Собрать образ и загрузить в Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./lab2/
          file: ./lab2/dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/antipina:latest

     
      - name: Deploy
        run: echo "Deployment step executed. Image pushed to Docker Hub."
